require('dotenv').config();

module.exports = {
  versionPattern: /(\d+\.)(\d+)(\.\d+|\-rc)/g,
  ticketPattern: /(([A-Z]{2,})-\d{1,})/g,
  csupPattern: /\[((CSUP)-\d{1,})\]/g,
  GITLAB_TOKEN: process.env.GITLAB_TOKEN,
  JIRA_USER: process.env.JIRA_USER,
  JIRA_PASSWD: process.env.JIRA_PASSWD,
  JIRA_PORT: "8443",
  JIRA_SERVER: "help.ssivt.com",
  JIRA_PROTOCOL: 'https',
  REPO_DIR: '/home/tnguye20/repo/enquesta/',
  CRM_URL:'https://help.ssivt.com:8443/plugins/servlet/crm/api',
  PROJECT_ID: process.env.PROJECT_ID,
  GITLAB_URL: `https://gitlab.ssivt.com/api/v4/projects/${process.env.PROJECT_ID}/`,
  GIT_SOURCE_BRANCH: "develop",
  GIT_MASTER_BRANCH: "master",
  CRM_KEYS:{
      "gitDevelopBranch"    : "clients_field_afbfe373-b5e1-4a71-a8b5-92f773192537",
      "gitMasterBranch"     : "clients_field_b00dc98e-b1df-41be-aa00-589ce654c994",
      "enQuestaVersion"     : "clients_field_901fc5f6-1abf-4481-929a-1333d186d1a7",
      "shortName"           : "clients_field_736dbe20-c77b-42e3-9669-f26f142e0e09",
      "enQuestaVersionTrain": "clients_field_7e98374b-b611-44c8-b6ef-58eb3a44c088"
  },
  COMPANY_KEY: "customfield_10712",
  BUG_ENV_KEY: "customfield_12400",
  TYPE_OF_RESOLUTION: "customfield_11100",
  FUNCTIONAL_AREA: "customfield_10809",
  IMPACT: "customfield_10500",
  REPLICATION_NOTE: "customfield_10119",
  ROOT_CAUSE: "customfield_10120",
  SS_COMPANY: "Systems And Software",
  SS_COMPANY_ID: "24",
  CUSTOMER_APPROVED: "Customer Approved",
  CLOSED: "Closed",
  CLOSED_: "Closed_",
  RD_MERGE_CODE_TO_CLOSE: "151",
  SU_MERGE_CODE_TO_CLOSE: "401",
  PS_MERGE_CODE_TO_CLOSE: "351",
  PASS_QA_BUILD_RELEASE: "1371",
  DEPLOY_TO_TRAIN_ID: "1361",
  DEPLOY_TO_TRAIN_ID_FROM_INTERNAL_TESTING: "1411",
  DEPLOY_TO_TRAIN_ID_FROM_READY_FOR_DEPLOYMENT: "1451",
  READY_FOR_DEPLOYMENT_FROM_INTERNAL_TESTING: "1441",
  DEPLOY_TO_PROD_ID: "1061",
  INTERNAL_TESTING_ID: "1401",
  FINALIZE_RELEASE_ID: "161",
  REVIEW_REQUIREMENTS: "31",
  RELEASE_TERMINATE_TRAIN: "1421",
  RELEASE_TERMINATE_INTERNAL: "1431",
  HOTFIX: "hotfix",
  RELEASEFIX: "release_bug_fix",
  RELEASE: "release",
  SHOWSTOPPER: "Showstopper",
}
